import os

from tplinkrouterc6u import TPLinkDecoClient


def generate_hosts_file(router_url, password, output_file="/etc/hosts"):
    """
    Connect to TPLink router, get device information, and generate a hosts file.
    
    Args:
        router_url (str): URL of the router (e.g., "http://10.1.0.1")
        password (str): Router password
        output_file (str): Path to output hosts file
    """
    # Connect to router and get device information
    router = TPLinkDecoClient(router_url, password)
    router.authorize()
    
    try:
        status = router.get_status()
        
        # Standard hosts file header
        hosts_content = [
            "# /etc/hosts file generated from TPLink router data",
            "# Generated by tp-link-deco/sync_devices.py script",
            "",
            "# localhost entries",
            "127.0.0.1   localhost",
            "::1         localhost ip6-localhost ip6-loopback",
            "ff02::1     ip6-allnodes",
            "ff02::2     ip6-allrouters",
            "",
            "# --- BEGIN Custom DNS ---",
            "10.1.0.200  adguard adguard.home",
        ]
        
        # Add each device from the router
        for device in status.devices:
            # Create properly formatted hosts entry
            # Ensure hostname is lowercase and remove spaces/special chars
            if device.ipaddr == "10.1.0.200":
                continue
            else:
                hostname = device.hostname.lower().replace(" ", "-")
                hosts_content.append(f"{device.ipaddr}\t{hostname}")
        
        # Add final newline
        hosts_content.append("# --- END Custom DNS ---",)
        
        # Write to file
        with open(output_file, 'w') as f:
            f.write('\n'.join(hosts_content))
            
    finally:
        # Ensure we always logout
        router.logout()


if __name__ == "__main__":
    # Get router password from environment variable
    router_password = os.getenv("TPLINK_PASSWORD")
    if not router_password:
        raise ValueError("TPLINK_PASSWORD environment variable must be set")
    
    generate_hosts_file("http://10.1.0.1", router_password)
